Sensorintegration
purduerov/XX-Core pull request #24
Opened 2018-02-27 05:47 UTC by AnotherOctopus

Integrates sensors

2018-02-28 23:55 UTC, bmaxfie requested changes
Along with comments in code. What are the recommended update frequencies for the IMU and Pressure sensor

2018-02-28 23:57 UTC, bmaxfie commented on rov/rov.py
> +        self.IMU = IMU()
Change self.IMU to self.imu

To keep to the convention of lowercase instances.

2018-03-01 00:08 UTC, bmaxfie requested changes
These are the changes I was talking about above... Whoops!

2018-03-01 00:08 UTC, bmaxfie commented on rov/rov.py
> +	    self.IMU.update()
Above

2018-03-01 00:08 UTC, bmaxfie commented on rov/rov.py
> +        self.dearclient['imu'] = self.IMU.data
Above

2018-03-01 00:08 UTC, bmaxfie commented on rov/sensors/pressure/BlueRobotics_Bar30.py
> +    def __init__(self,PressDepthConv=0.01):
If PressDepthConv is useful to us, add comments saying how to use it!

2018-03-01 00:08 UTC, bmaxfie commented on rov/sensors/pressure/BlueRobotics_Bar30.py
>          time.sleep(0.5)
You left this line here??? Why?

2018-03-01 00:08 UTC, bmaxfie commented on rov/sensors/pressure/README.md
> -### Return Data:
A++++++ README THO

2018-03-01 00:08 UTC, bmaxfie commented on surface/frontend/src/packets.js
> -        pressure: {
Where does pressure go now? Or at least what is its format?

2018-03-01 00:08 UTC, bmaxfie commented on tests/rov_pressure_test.py
> +            print("%s \t%0.1f \t%0.2f") % (time.strftime("%H:%M:%S", time.localtime()) + '.%d' % (time.time() % 1 * 1000),
So the tests/ folder is primarily for Unit Tests. This seems more like just a start script. This is good to have. I would put this exact code at the bottom of the pressure code under a `if __name__ == '__main__':` so we can make it run by running the ms5837 file. And make another for the tests/ folder that just checks whether a reasonable value is generated from the sensor and whether it changes. I think that would be a good enough Unit Test that the sensor code is working (for automated testing).

2018-03-01 00:08 UTC, bmaxfie commented on rov/sensors/pressure/BlueRobotics_Bar30.py
>  class Pressure(object):
What is the difference between this file and the ms5837 file?

2018-03-02 22:42 UTC, mattmolo commented on rov/sensors/imu/BNO055.py
> +	gyro = self._bno.read_gyroscope()
there's a tab here

2018-03-19 18:17 UTC, bmaxfie commented
@MoldingTofu Confirmation the sensor works? I know the frequency/accuracy test hasn't been performed yet, but I can merge as long as its working.

2018-03-19 19:09 UTC, AnotherOctopus commented
@bmaxfie I did the frequency test, with an accuracy check using the pressure chambers gauge on top, and it seemed to be fine. I posted about it in SW general

2018-03-19 22:03 UTC, bmaxfie commented
I see it now. This is good. Okay. Refresh rate of 5 ms is perfect.

2018-03-19 22:04 UTC, bmaxfie commented
Just need IMU to imu fix and I think it'll be set?

2018-03-20 14:27 UTC, AnotherOctopus commented
@bmaxfie IMU update pushed

2018-03-21 22:29 UTC, bmaxfie approved these changes

2018-03-21 22:29 UTC, merged